version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: luo147258
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user:
    container_name: user
    build:
      context: ./apps/user
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/user:/app
      - ./libs:/app/libs
      - /app/node_modules
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: luo147258
      DATABASE_NAME: mydb
      JWT_SECRET: kunsong
      JWT_EXPIRES_IN: 60m
    command: pnpm run start
    depends_on:
      - postgres

  auth:
    container_name: auth
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    volumes:
      - ./apps/auth:/app
      - ./libs:/app/libs
      - /app/node_modules
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: luo147258
      DATABASE_NAME: mydb
      JWT_SECRET: kunsong
      JWT_EXPIRES_IN: 60m
    ports:
      - "3001:3001"
    command: pnpm run start
    depends_on:
      - postgres

volumes:
  postgres_data:
